//List of plants from the api
//Data array not actually being used in app
const nameData = [
    'Lipstick',
    'Maindenhair', 'Delta maidenhair',
    'Silver vase', 'Silver vase',
    'Variegated Carabbean Agave', 'Century plant',
    'Coral berry',
    'Thread Agave', 'Century plant',
    'Rosy Maidenhair', 'Autralian maidenhair',
    'Dragon tree Agave', 'Century plant',
    'Chinese Evergreen', 'Amelia',
    'Chinese Evergreen', 'Painted Princess',
    'Chinese Evergreen', 'Queen of Siam',
    'Chinese Evergreen', 'Jewel of India',
    'Chinese Evergreen', 'Patricia',
    'Chinese Evergreen', 'Green Lady',
    'Chinese Evergreen', 'Black Lance',
    'Chinese Evergreen', 'Silver Queen',
    'Chinese Evergreen', 'Rapsody in Green',
    'Chinese Evergreen', 'Manila Pride',
    'Blue Agave', 'Century plant',
    'Chinese Evergreen', 'Emerald Beauty',
    'Chinese Evergreen', 'Jubilee',
    'Lilliput Agave', 'Century plant', 'Nana',
    'Chinese Evergreen', 'Abidjan',
    'Chinese Evergreen', 'Maria Chirstina',
    'Chinese Evergreen', 'Emerald Isle',
    'Chinese Evergreen', 'Mary Ann',
    'Golden Trumpet',
    'Chinese Evergreen', 'BJ Freeman',
    'Chinese Evergreen', 'Marguerita',
    'Chinese Evergreen', 'Emerald Star',
    'Chinese Evergreen', 'Silver Bay',
    'Cast iron plant',
    'Bronze Anthurium',
    'Fish tail palm',
    'Croton',
    'Tree Cereus',
    'Miniature tree fern', 'Dwarf tree fern',
    'Bella palm', 'Neanthebella palm', 'Dwarf palm', 'Parlor palm',
    'Medallion Calathea',
    'Silver Calathea',
    'Bougainvillia', 'Paper flower',
    'Bamboo palm', 'Reed Palm',
    'Tailflower', 'Wax flower',
    'Bird nest Anthurium', 'Cabbage Anthurium',
    'Grape Ivy', 'Ellen Danica',
    'Monster cactus',
    'Bamboo palm',
    'Stromante',
    'Croton',
    'Velvet Calathea',
    'Jade Plant',
    'Elephant ear',
    'Grape Ivy',
    'Bird nest Anthurium', 'Cabbage Anthurium',
    'Miniature fishtail', 'Steel palm',
    'Cast iron plant', 'Aspidistra Milky Way',
    'Stiped calathea',
    'Birdnest fern',
    'Bird nest Anthurium', 'Cabbage Anthurium',
    'Spider plant',
    'Tree Maindenhair fern',
    'Dumcane', 'Tropic Mary Ann',
    'Dumcane', 'Star Bright',
    'Madagascar dragon tree', 'Tricolor',
    'Cornstalk plant',
    'Janet Craig',
    'Yellow Malaysian Dracaena', 'Song of India',
    'Dumcane', 'Carina',
    'Malaysian Dracaena', 'Song of Jamaica',
    'Sago palm', 'King sago',
    'Jade Plant',
    'Phrynium',
    'Malaysian Dracaena',
    'Striped Dracaena', 'Gold Star',
    'Holly-fern',
    'Dwarf bouquet', 'Calypso Queen', 'Janet Craig Compacta',
    'Rabbits foot', 'Squirrels foot',
    'Lisa Dracaena', 'Lisa',
    'Madagascar dragon tree',
    'Striped Dracaena', 'Warneckei',
    'Striped Dracaena', 'Lemon Lime',
    'Dumcane', 'Camille',
    'Dumcane', 'Tropic Snow',
    'Rubber plant', 'Tineke',
    'Areca palm', 'Butterfly palm',
    'Orchid cactus',
    'Golden Barrel',
    'Christ thorn', 'Crown of thorns',
    'White Pothos', 'Marble Queen',
    'Guzmania', 'Guzmania Sunnytime',
    'Willow fig tree', 'Amstel King',
    'Guzmania', 'Guzmania Empire',
    'Weeping fig',
    'Japanese Aralia',
    'Variegated Euphorbia',
    'Creeping fig', 'Curl',
    'Guzmania', 'Claret',
    'Rubber plant', 'Robusta',
    'Algerian ivy', 'Montgomery ivy',
    'Golden Pothos',
    'Fidleleaf fig',
    'Giant Candelabra tree',
    'Weeping fig', 'Monique',
    'Guzmania', 'Mariposa',
    'Willow Ficus',
    'Guzmania', 'Marjan',
    'Weeping fig', 'Midnight',
    'Guzmania', 'Rana',
    'Rubber plant', 'Burgandy',
    'English ivy', 'Gold Baby',
    'Herringbone', 'Pink praying plant',
    'English ivy', 'Hermania',
    'Splitleaf Philodendron', 'Mexican Breadfruit',
    'Baby rubber plant', 'Pepper face',
    'Snakes beard',
    'Butterfly Ginger', 'White Ginger',
    'English ivy', 'Variegated English ivy',
    'English ivy', 'Garland',
    'Wax plant',
    'Oleander', 'Rose bay',
    'Madagascar Palm',
    'Spiny licuala palm',
    'Red Philodendron', 'Imperial Red',
    'Variegated lily turf',
    'Velvet leaf vine',
    'Green prayer plant', 'Herringbone',
    'Elephant foot', 'Pony tail',
    'Lime philodendron', 'Moonlight',
    'Spindle palm',
    'English ivy',
    'Rose grape',
    'Chinese hibiscus',
    'Boston fern', 'Sword fern',
    'Kentia palm', 'Paradise palm',
    'Emerald Prince',
    'Emerald Gem',
    'Tricolor Peperomia',
    'Bower plant', 'Bower of beauty',
    'China doll',
    'Cretan brake',
    'Korean rock fern', 'Tsu sima holly fern',
    'Japanese tassel fern',
    'Majesty palm',
    'Fabian Aralia', 'Red Aralia',
    'Silver Ribbon Fern',
    'Staghorn fern',
    'Balfour aralia', 'Aralia Balfouriana', 'Lemon Lime',
    'Snake plant',
    'Fernleaf Philodendron',
    'African fern pine', 'Buddhist pine',
    'Birdnest sansevieria', 'Snake plant',
    'Snake plant',
    'Chicken gizard aralia',
    'Pignee Date palm',
    'Variegated Balfour aralia', 'Aralia Balfouriana',
    'Ming Aralia', 'Parsley panax',
    'Lacy tree philodendron',
    'Silver Lace Fern',
    'Lady palm',
    'Ming Aralia', 'Parsley panax',
    'Parlor ivy', 'Sweetheart plant', 'Heartleaf philodendron', 'Cordatum vine',
    'Adonidia', 'Christmas palm', 'Manila palm',
    'Cape mahogany', 'Christmas bells',
    'African evergreen', 'Arrowhead vine', 'Goosefoot plant', 'White Lightning',
    'Parrot palm',
    'Pink quill',
    'Indian kale',
    'False aralia',
    'Peace lily',
    'Burro tail',
    'African evergreen', 'Arrowhead vine', 'Goosefoot plant', 'Pink Allusion',
    'Picta Philodendron', 'Satin pothos', 'Devils ivy',
    'Grass tree',
    'Yellow Hawaiian elf', 'Yellow parasol plant',
    'Umbella plant',
    'Umbella plant',
    'Snake plant',
    'Peace lily', 'Emerald Swirl',
    'Hawaiian elf', 'Parasol plant', 'Gold Cappela',
    'White bird of paradise',
    'Zz plant',
    'Spineless yucca', 'Palm lily'
];

//Photo gallery data
//Graphical content from unslpash.com
const photoGallery = [
    {   id: 1, 
        url: './img/carrots.jpg', 
        caption: 'Carrots' },
    { 
        id: 2, 
        url: './img/beetroot.jpg', 
        caption: 'Beetroot' },

    {   id: 3, 
        url: './img/pepper.jpg', 
        caption: 'Pepper' },
    {
        id: 4,
        url: './img/peacelily.jpg',
        caption: 'Peace lily' },
    {
        id: 5,
        url: './img/oleander.jpg',
        caption: 'Oleander' },
    {
        id: 6,
        url: './img/jadeplant.jpg',
        caption: 'Jade plant' }
  ];

 